server:
  port: ${PORT:8080}
  tomcat:
    accesslog:
      enabled: false
    basedir: logs

logging:
  file:
    name: logs/${spring.application.name}.log
    max-size: 1GB
    max-history: 365
  level:
    root: info
    org.zalando.logbook: trace
    com.sgedts.indomarcosurvey: debug
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG

spring:
  application:
    name: jpaQuery
  profiles:
    active: default
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/query;DB_CLOSE_DELAY=-1
    username: query
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      # disable spring boot built-in h2-console since we start it manually with correct configuration
      enabled: true
  codec.max-in-memory-size: 20MB

  # Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
host:
  ip: localhost
  port: ${server.port}
  path: ""

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization,Link,X-Total-Count"
  allow-credentials: true
  max-age: 18000
swagger:
  host: ${host.ip}:${host.port}
  path: /${host.path}
#  data:
#    web:
#      pageable:
#        page-parameter: pageNumber
#        size-parameter: pageSize
#        one-indexed-parameters: true
#        default-page-size: 10
#        max-page-size: 50

#ACTUATOR
# management.endpoints.web.exposure.include=*

# ========== custom property =============
application:
  description: ^project.description^
  version: ^project.version^
